# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network requests to Google Analytics.
# To disable this, uncomment the following line.
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'

source 'https://cdn.cocoapods.org/'

# CocoaPods analytics sends network requests to Google Analytics.
# To disable this, uncomment the following line.
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return {}
  end

  generated_key_values = {}
  File.foreach(file_abs_path) do |line|
    stripped_line = line.strip
    if !stripped_line.empty?
      key_value = stripped_line.split(separator, 2)
      if key_value.length == 2
        generated_key_values[key_value[0].strip] = key_value[1].strip
      else
        puts "No valid key value pair found in line: #{line}"
      end
    end
  end
  generated_key_values
end

# Parse podspec key/value for a specific podspec key.
def parse_podspec_key_value(file, key)
  key_value_regex = Regexp.new("^#{key}\\s*=\\s*(.*)$", Regexp::IGNORECASE)
  data = ''
  File.foreach(file) do |line|
    if key_value_regex.match(line)
      data = $1
      break
    end
  end
  data.strip
end

# Prepare symlinks for Flutter framework
prepare_command = <<-CMD
  #!/bin/sh
  # Use sed to replace the placeholder version with the actual version
  sed -i '' 's/__FLUTTER_VERSION__/$(flutter --version | head -n 1 | cut -d' ' -f2)/g' #{Pod::Config.instance.installation_root}/symlinks/flutter/ios-release/Flutter.podspec
CMD

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '5.0'
      
      # Fix for Flutter 3.x
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
    end
  end
end
